// AUTO-GENERATED. DO NOT EDIT.
// Regenerate with: pnpm --filter @syntraodbc/drizzle-schema run generate
//
// Source: schemas/quickbooks.json
// Table:  credit_memos (89 columns)

import { pgTable, boolean, date, integer, numeric, timestamp, varchar } from 'drizzle-orm/pg-core';

export const credit_memos = pgTable('credit_memos', {
  txn_id: varchar('txn_id', { length: 36 }),
  time_created: timestamp('time_created', { withTimezone: false, mode: 'string' }),
  time_modified: timestamp('time_modified', { withTimezone: false, mode: 'string' }),
  edit_sequence: varchar('edit_sequence', { length: 16 }),
  txn_number: integer('txn_number'),
  customer_ref_list_id: varchar('customer_ref_list_id', { length: 36 }),
  customer_ref_full_name: varchar('customer_ref_full_name', { length: 209 }),
  class_ref_list_id: varchar('class_ref_list_id', { length: 36 }),
  class_ref_full_name: varchar('class_ref_full_name', { length: 209 }),
  ar_account_ref_list_id: varchar('ar_account_ref_list_id', { length: 36 }),
  ar_account_ref_full_name: varchar('ar_account_ref_full_name', { length: 209 }),
  template_ref_list_id: varchar('template_ref_list_id', { length: 36 }),
  template_ref_full_name: varchar('template_ref_full_name', { length: 209 }),
  txn_date: date('txn_date'),
  ref_number: varchar('ref_number', { length: 11 }),
  bill_address_addr1: varchar('bill_address_addr1', { length: 41 }),
  bill_address_addr2: varchar('bill_address_addr2', { length: 41 }),
  bill_address_addr3: varchar('bill_address_addr3', { length: 41 }),
  bill_address_addr4: varchar('bill_address_addr4', { length: 41 }),
  bill_address_addr5: varchar('bill_address_addr5', { length: 41 }),
  bill_address_city: varchar('bill_address_city', { length: 31 }),
  bill_address_state: varchar('bill_address_state', { length: 21 }),
  bill_address_postal_code: varchar('bill_address_postal_code', { length: 13 }),
  bill_address_country: varchar('bill_address_country', { length: 31 }),
  bill_address_note: varchar('bill_address_note', { length: 41 }),
  bill_address_block_addr1: varchar('bill_address_block_addr1', { length: 41 }),
  bill_address_block_addr2: varchar('bill_address_block_addr2', { length: 41 }),
  bill_address_block_addr3: varchar('bill_address_block_addr3', { length: 41 }),
  bill_address_block_addr4: varchar('bill_address_block_addr4', { length: 41 }),
  bill_address_block_addr5: varchar('bill_address_block_addr5', { length: 41 }),
  ship_address_addr1: varchar('ship_address_addr1', { length: 41 }),
  ship_address_addr2: varchar('ship_address_addr2', { length: 41 }),
  ship_address_addr3: varchar('ship_address_addr3', { length: 41 }),
  ship_address_addr4: varchar('ship_address_addr4', { length: 41 }),
  ship_address_addr5: varchar('ship_address_addr5', { length: 41 }),
  ship_address_city: varchar('ship_address_city', { length: 31 }),
  ship_address_state: varchar('ship_address_state', { length: 21 }),
  ship_address_postal_code: varchar('ship_address_postal_code', { length: 13 }),
  ship_address_country: varchar('ship_address_country', { length: 31 }),
  ship_address_note: varchar('ship_address_note', { length: 41 }),
  ship_address_block_addr1: varchar('ship_address_block_addr1', { length: 41 }),
  ship_address_block_addr2: varchar('ship_address_block_addr2', { length: 41 }),
  ship_address_block_addr3: varchar('ship_address_block_addr3', { length: 41 }),
  ship_address_block_addr4: varchar('ship_address_block_addr4', { length: 41 }),
  ship_address_block_addr5: varchar('ship_address_block_addr5', { length: 41 }),
  is_pending: boolean('is_pending'),
  po_number: varchar('po_number', { length: 25 }),
  terms_ref_list_id: varchar('terms_ref_list_id', { length: 36 }),
  terms_ref_full_name: varchar('terms_ref_full_name', { length: 209 }),
  due_date: date('due_date'),
  sales_rep_ref_list_id: varchar('sales_rep_ref_list_id', { length: 36 }),
  sales_rep_ref_full_name: varchar('sales_rep_ref_full_name', { length: 209 }),
  fob: varchar('fob', { length: 13 }),
  ship_date: date('ship_date'),
  ship_method_ref_list_id: varchar('ship_method_ref_list_id', { length: 36 }),
  ship_method_ref_full_name: varchar('ship_method_ref_full_name', { length: 209 }),
  subtotal: numeric('subtotal', { precision: 12, scale: 2 }),
  item_sales_tax_ref_list_id: varchar('item_sales_tax_ref_list_id', { length: 36 }),
  item_sales_tax_ref_full_name: varchar('item_sales_tax_ref_full_name', { length: 209 }),
  sales_tax_percentage: numeric('sales_tax_percentage', { precision: 12, scale: 4 }),
  sales_tax_total: numeric('sales_tax_total', { precision: 12, scale: 2 }),
  total_amount: numeric('total_amount', { precision: 12, scale: 2 }),
  credit_remaining: numeric('credit_remaining', { precision: 12, scale: 2 }),
  currency_ref_list_id: varchar('currency_ref_list_id', { length: 36 }),
  currency_ref_full_name: varchar('currency_ref_full_name', { length: 209 }),
  exchange_rate: numeric('exchange_rate', { precision: 12, scale: 4 }),
  credit_remaining_in_home_currency: numeric('credit_remaining_in_home_currency', { precision: 12, scale: 2 }),
  memo: varchar('memo', { length: 4095 }),
  customer_msg_ref_list_id: varchar('customer_msg_ref_list_id', { length: 36 }),
  customer_msg_ref_full_name: varchar('customer_msg_ref_full_name', { length: 209 }),
  is_to_be_printed: boolean('is_to_be_printed'),
  is_to_be_emailed: boolean('is_to_be_emailed'),
  is_tax_included: boolean('is_tax_included'),
  customer_sales_tax_code_ref_list_id: varchar('customer_sales_tax_code_ref_list_id', { length: 36 }),
  customer_sales_tax_code_ref_full_name: varchar('customer_sales_tax_code_ref_full_name', { length: 209 }),
  other: varchar('other', { length: 29 }),
  external_guid: varchar('external_guid', { length: 36 }),
  discount_line_ret_amount: numeric('discount_line_ret_amount', { precision: 12, scale: 2 }),
  discount_line_ret_rate_percent: numeric('discount_line_ret_rate_percent', { precision: 12, scale: 4 }),
  discount_line_ret_is_taxable: boolean('discount_line_ret_is_taxable'),
  discount_line_ret_account_ref_list_id: varchar('discount_line_ret_account_ref_list_id', { length: 36 }),
  discount_line_ret_account_ref_full_name: varchar('discount_line_ret_account_ref_full_name', { length: 209 }),
  sales_tax_line_ret_amount: numeric('sales_tax_line_ret_amount', { precision: 12, scale: 2 }),
  sales_tax_line_ret_rate_percent: numeric('sales_tax_line_ret_rate_percent', { precision: 12, scale: 4 }),
  sales_tax_line_ret_account_ref_list_id: varchar('sales_tax_line_ret_account_ref_list_id', { length: 36 }),
  sales_tax_line_ret_account_ref_full_name: varchar('sales_tax_line_ret_account_ref_full_name', { length: 209 }),
  shipping_line_ret_amount: numeric('shipping_line_ret_amount', { precision: 12, scale: 2 }),
  shipping_line_ret_account_ref_list_id: varchar('shipping_line_ret_account_ref_list_id', { length: 36 }),
  shipping_line_ret_account_ref_full_name: varchar('shipping_line_ret_account_ref_full_name', { length: 209 }),
});

export type CreditMemos = typeof credit_memos.$inferSelect;
export type NewCreditMemos = typeof credit_memos.$inferInsert;
