// AUTO-GENERATED. DO NOT EDIT.
// Regenerate with: pnpm --filter @syntraodbc/drizzle-schema run generate
//
// Source: schemas/quickbooks.json
// Table:  customers (95 columns)

import { pgTable, boolean, date, integer, numeric, text, timestamp, varchar } from 'drizzle-orm/pg-core';

export const customers = pgTable('customers', {
  list_id: varchar('list_id', { length: 36 }),
  time_created: timestamp('time_created', { withTimezone: false, mode: 'string' }),
  time_modified: timestamp('time_modified', { withTimezone: false, mode: 'string' }),
  edit_sequence: varchar('edit_sequence', { length: 16 }),
  name: varchar('name', { length: 41 }),
  full_name: varchar('full_name', { length: 209 }),
  is_active: boolean('is_active'),
  class_ref_list_id: varchar('class_ref_list_id', { length: 36 }),
  class_ref_full_name: varchar('class_ref_full_name', { length: 209 }),
  parent_ref_list_id: varchar('parent_ref_list_id', { length: 36 }),
  parent_ref_full_name: varchar('parent_ref_full_name', { length: 209 }),
  sublevel: integer('sublevel'),
  company_name: varchar('company_name', { length: 41 }),
  salutation: varchar('salutation', { length: 15 }),
  first_name: varchar('first_name', { length: 25 }),
  middle_name: varchar('middle_name', { length: 5 }),
  last_name: varchar('last_name', { length: 25 }),
  suffix: text('suffix'),
  job_title: varchar('job_title', { length: 41 }),
  bill_address_addr1: varchar('bill_address_addr1', { length: 41 }),
  bill_address_addr2: varchar('bill_address_addr2', { length: 41 }),
  bill_address_addr3: varchar('bill_address_addr3', { length: 41 }),
  bill_address_addr4: varchar('bill_address_addr4', { length: 41 }),
  bill_address_addr5: varchar('bill_address_addr5', { length: 41 }),
  bill_address_city: varchar('bill_address_city', { length: 31 }),
  bill_address_state: varchar('bill_address_state', { length: 21 }),
  bill_address_postal_code: varchar('bill_address_postal_code', { length: 13 }),
  bill_address_country: varchar('bill_address_country', { length: 31 }),
  bill_address_note: varchar('bill_address_note', { length: 41 }),
  bill_address_block_addr1: varchar('bill_address_block_addr1', { length: 41 }),
  bill_address_block_addr2: varchar('bill_address_block_addr2', { length: 41 }),
  bill_address_block_addr3: varchar('bill_address_block_addr3', { length: 41 }),
  bill_address_block_addr4: varchar('bill_address_block_addr4', { length: 41 }),
  bill_address_block_addr5: varchar('bill_address_block_addr5', { length: 41 }),
  ship_address_addr1: varchar('ship_address_addr1', { length: 41 }),
  ship_address_addr2: varchar('ship_address_addr2', { length: 41 }),
  ship_address_addr3: varchar('ship_address_addr3', { length: 41 }),
  ship_address_addr4: varchar('ship_address_addr4', { length: 41 }),
  ship_address_addr5: varchar('ship_address_addr5', { length: 41 }),
  ship_address_city: varchar('ship_address_city', { length: 31 }),
  ship_address_state: varchar('ship_address_state', { length: 21 }),
  ship_address_postal_code: varchar('ship_address_postal_code', { length: 13 }),
  ship_address_country: varchar('ship_address_country', { length: 31 }),
  ship_address_note: varchar('ship_address_note', { length: 41 }),
  ship_address_block_addr1: varchar('ship_address_block_addr1', { length: 41 }),
  ship_address_block_addr2: varchar('ship_address_block_addr2', { length: 41 }),
  ship_address_block_addr3: varchar('ship_address_block_addr3', { length: 41 }),
  ship_address_block_addr4: varchar('ship_address_block_addr4', { length: 41 }),
  ship_address_block_addr5: varchar('ship_address_block_addr5', { length: 41 }),
  print_as: varchar('print_as', { length: 41 }),
  phone: varchar('phone', { length: 21 }),
  mobile: varchar('mobile', { length: 21 }),
  pager: varchar('pager', { length: 21 }),
  alt_phone: varchar('alt_phone', { length: 21 }),
  fax: varchar('fax', { length: 21 }),
  email: varchar('email', { length: 1023 }),
  cc: varchar('cc', { length: 1023 }),
  contact: varchar('contact', { length: 41 }),
  alt_contact: varchar('alt_contact', { length: 41 }),
  customer_type_ref_list_id: varchar('customer_type_ref_list_id', { length: 36 }),
  customer_type_ref_full_name: varchar('customer_type_ref_full_name', { length: 209 }),
  terms_ref_list_id: varchar('terms_ref_list_id', { length: 36 }),
  terms_ref_full_name: varchar('terms_ref_full_name', { length: 209 }),
  sales_rep_ref_list_id: varchar('sales_rep_ref_list_id', { length: 36 }),
  sales_rep_ref_full_name: varchar('sales_rep_ref_full_name', { length: 209 }),
  balance: numeric('balance', { precision: 12, scale: 2 }),
  total_balance: numeric('total_balance', { precision: 12, scale: 2 }),
  sales_tax_code_ref_list_id: varchar('sales_tax_code_ref_list_id', { length: 36 }),
  sales_tax_code_ref_full_name: varchar('sales_tax_code_ref_full_name', { length: 209 }),
  item_sales_tax_ref_list_id: varchar('item_sales_tax_ref_list_id', { length: 36 }),
  item_sales_tax_ref_full_name: varchar('item_sales_tax_ref_full_name', { length: 209 }),
  resale_number: varchar('resale_number', { length: 15 }),
  account_number: varchar('account_number', { length: 99 }),
  credit_limit: numeric('credit_limit', { precision: 12, scale: 2 }),
  preferred_payment_method_ref_list_id: varchar('preferred_payment_method_ref_list_id', { length: 36 }),
  preferred_payment_method_ref_full_name: varchar('preferred_payment_method_ref_full_name', { length: 209 }),
  credit_card_info_credit_card_number: varchar('credit_card_info_credit_card_number', { length: 25 }),
  credit_card_info_expiration_year: integer('credit_card_info_expiration_year'),
  credit_card_info_name_on_card: varchar('credit_card_info_name_on_card', { length: 41 }),
  credit_card_info_credit_card_address: varchar('credit_card_info_credit_card_address', { length: 41 }),
  credit_card_info_credit_card_postal_code: varchar('credit_card_info_credit_card_postal_code', { length: 41 }),
  job_start_date: date('job_start_date'),
  job_projected_end_date: date('job_projected_end_date'),
  job_end_date: date('job_end_date'),
  job_desc: varchar('job_desc', { length: 99 }),
  job_type_ref_list_id: varchar('job_type_ref_list_id', { length: 36 }),
  job_type_ref_full_name: varchar('job_type_ref_full_name', { length: 209 }),
  notes: varchar('notes', { length: 4095 }),
  is_statement_with_parent: boolean('is_statement_with_parent'),
  price_level_ref_list_id: varchar('price_level_ref_list_id', { length: 36 }),
  price_level_ref_full_name: varchar('price_level_ref_full_name', { length: 209 }),
  external_guid: varchar('external_guid', { length: 36 }),
  tax_registration_number: varchar('tax_registration_number', { length: 30 }),
  currency_ref_list_id: varchar('currency_ref_list_id', { length: 36 }),
  currency_ref_full_name: varchar('currency_ref_full_name', { length: 209 }),
});

export type Customers = typeof customers.$inferSelect;
export type NewCustomers = typeof customers.$inferInsert;
