// AUTO-GENERATED. DO NOT EDIT.
// Regenerate with: pnpm --filter @syntraodbc/drizzle-schema run generate
//
// Source: schemas/quickbooks.json
// Table:  employees (64 columns)

import { pgTable, boolean, date, numeric, text, timestamp, varchar } from 'drizzle-orm/pg-core';

export const employees = pgTable('employees', {
  list_id: varchar('list_id', { length: 36 }),
  time_created: timestamp('time_created', { withTimezone: false, mode: 'string' }),
  time_modified: timestamp('time_modified', { withTimezone: false, mode: 'string' }),
  edit_sequence: varchar('edit_sequence', { length: 16 }),
  name: varchar('name', { length: 41 }),
  is_active: boolean('is_active'),
  salutation: varchar('salutation', { length: 15 }),
  first_name: varchar('first_name', { length: 25 }),
  middle_name: varchar('middle_name', { length: 5 }),
  last_name: varchar('last_name', { length: 25 }),
  suffix: text('suffix'),
  job_title: varchar('job_title', { length: 41 }),
  supervisor_ref_list_id: varchar('supervisor_ref_list_id', { length: 36 }),
  supervisor_ref_full_name: varchar('supervisor_ref_full_name', { length: 209 }),
  department: varchar('department', { length: 31 }),
  description: varchar('description', { length: 64 }),
  target_bonus: numeric('target_bonus', { precision: 12, scale: 2 }),
  employee_address_addr1: varchar('employee_address_addr1', { length: 41 }),
  employee_address_addr2: varchar('employee_address_addr2', { length: 41 }),
  employee_address_addr3: text('employee_address_addr3'),
  employee_address_addr4: text('employee_address_addr4'),
  employee_address_city: varchar('employee_address_city', { length: 31 }),
  employee_address_state: varchar('employee_address_state', { length: 21 }),
  employee_address_postal_code: varchar('employee_address_postal_code', { length: 13 }),
  employee_address_country: text('employee_address_country'),
  print_as: varchar('print_as', { length: 41 }),
  phone: varchar('phone', { length: 21 }),
  mobile: varchar('mobile', { length: 21 }),
  pager: varchar('pager', { length: 21 }),
  pager_pin: varchar('pager_pin', { length: 10 }),
  alt_phone: varchar('alt_phone', { length: 21 }),
  fax: varchar('fax', { length: 21 }),
  ssn: varchar('ssn', { length: 11 }),
  email: varchar('email', { length: 1023 }),
  hired_date: date('hired_date'),
  original_hire_date: date('original_hire_date'),
  adjusted_service_date: date('adjusted_service_date'),
  released_date: date('released_date'),
  birth_date: date('birth_date'),
  disability_desc: varchar('disability_desc', { length: 25 }),
  work_auth_expire_date: date('work_auth_expire_date'),
  account_number: varchar('account_number', { length: 99 }),
  notes: varchar('notes', { length: 4095 }),
  billing_rate_ref_list_id: varchar('billing_rate_ref_list_id', { length: 36 }),
  billing_rate_ref_full_name: varchar('billing_rate_ref_full_name', { length: 209 }),
  employee_payroll_info_is_covered_by_qualified_pension_plan: boolean('employee_payroll_info_is_covered_by_qualified_pension_plan'),
  employee_payroll_info_pay_schedule_ref_list_id: varchar('employee_payroll_info_pay_schedule_ref_list_id', { length: 36 }),
  employee_payroll_info_pay_schedule_ref_full_name: varchar('employee_payroll_info_pay_schedule_ref_full_name', { length: 209 }),
  employee_payroll_info_class_ref_list_id: varchar('employee_payroll_info_class_ref_list_id', { length: 36 }),
  employee_payroll_info_class_ref_full_name: varchar('employee_payroll_info_class_ref_full_name', { length: 209 }),
  employee_payroll_info_clear_earnings: boolean('employee_payroll_info_clear_earnings'),
  employee_payroll_info_clear_non_earnings: boolean('employee_payroll_info_clear_non_earnings'),
  employee_payroll_info_sick_hours_is_resetting_hours_each_new_year: boolean('employee_payroll_info_sick_hours_is_resetting_hours_each_new_year'),
  employee_payroll_info_sick_hours_year_begins_date: date('employee_payroll_info_sick_hours_year_begins_date'),
  employee_payroll_info_sick_hours_accrual_start_date: date('employee_payroll_info_sick_hours_accrual_start_date'),
  employee_payroll_info_vacation_hours_is_resetting_hours_each_new_year: boolean('employee_payroll_info_vacation_hours_is_resetting_hours_each_new_year'),
  employee_payroll_info_vacation_hours_year_begins_date: date('employee_payroll_info_vacation_hours_year_begins_date'),
  employee_payroll_info_vacation_hours_accrual_start_date: date('employee_payroll_info_vacation_hours_accrual_start_date'),
  employee_payroll_info_employee_tax_info_state_lived: varchar('employee_payroll_info_employee_tax_info_state_lived', { length: 21 }),
  employee_payroll_info_employee_tax_info_state_worked: varchar('employee_payroll_info_employee_tax_info_state_worked', { length: 21 }),
  employee_payroll_info_employee_tax_info_is_standard_taxation_required: boolean('employee_payroll_info_employee_tax_info_is_standard_taxation_required'),
  employee_payroll_info_workers_comp_code_ref_list_id: varchar('employee_payroll_info_workers_comp_code_ref_list_id', { length: 36 }),
  employee_payroll_info_workers_comp_code_ref_full_name: varchar('employee_payroll_info_workers_comp_code_ref_full_name', { length: 209 }),
  external_guid: varchar('external_guid', { length: 36 }),
});

export type Employees = typeof employees.$inferSelect;
export type NewEmployees = typeof employees.$inferInsert;
