// AUTO-GENERATED. DO NOT EDIT.
// Regenerate with: pnpm --filter @syntraodbc/drizzle-schema run generate
//
// Source: schemas/quickbooks.json
// Table:  purchase_orders (71 columns)

import { pgTable, boolean, date, integer, numeric, timestamp, varchar } from 'drizzle-orm/pg-core';

export const purchase_orders = pgTable('purchase_orders', {
  txn_id: varchar('txn_id', { length: 36 }),
  time_created: timestamp('time_created', { withTimezone: false, mode: 'string' }),
  time_modified: timestamp('time_modified', { withTimezone: false, mode: 'string' }),
  edit_sequence: varchar('edit_sequence', { length: 16 }),
  txn_number: integer('txn_number'),
  vendor_ref_list_id: varchar('vendor_ref_list_id', { length: 36 }),
  vendor_ref_full_name: varchar('vendor_ref_full_name', { length: 209 }),
  class_ref_list_id: varchar('class_ref_list_id', { length: 36 }),
  class_ref_full_name: varchar('class_ref_full_name', { length: 209 }),
  inventory_site_ref_list_id: varchar('inventory_site_ref_list_id', { length: 36 }),
  inventory_site_ref_full_name: varchar('inventory_site_ref_full_name', { length: 209 }),
  ship_to_entity_ref_list_id: varchar('ship_to_entity_ref_list_id', { length: 36 }),
  ship_to_entity_ref_full_name: varchar('ship_to_entity_ref_full_name', { length: 209 }),
  template_ref_list_id: varchar('template_ref_list_id', { length: 36 }),
  template_ref_full_name: varchar('template_ref_full_name', { length: 209 }),
  txn_date: date('txn_date'),
  ref_number: varchar('ref_number', { length: 11 }),
  vendor_address_addr1: varchar('vendor_address_addr1', { length: 41 }),
  vendor_address_addr2: varchar('vendor_address_addr2', { length: 41 }),
  vendor_address_addr3: varchar('vendor_address_addr3', { length: 41 }),
  vendor_address_addr4: varchar('vendor_address_addr4', { length: 41 }),
  vendor_address_addr5: varchar('vendor_address_addr5', { length: 41 }),
  vendor_address_city: varchar('vendor_address_city', { length: 31 }),
  vendor_address_state: varchar('vendor_address_state', { length: 21 }),
  vendor_address_postal_code: varchar('vendor_address_postal_code', { length: 13 }),
  vendor_address_country: varchar('vendor_address_country', { length: 31 }),
  vendor_address_note: varchar('vendor_address_note', { length: 41 }),
  vendor_address_block_addr1: varchar('vendor_address_block_addr1', { length: 41 }),
  vendor_address_block_addr2: varchar('vendor_address_block_addr2', { length: 41 }),
  vendor_address_block_addr3: varchar('vendor_address_block_addr3', { length: 41 }),
  vendor_address_block_addr4: varchar('vendor_address_block_addr4', { length: 41 }),
  vendor_address_block_addr5: varchar('vendor_address_block_addr5', { length: 41 }),
  ship_address_addr1: varchar('ship_address_addr1', { length: 41 }),
  ship_address_addr2: varchar('ship_address_addr2', { length: 41 }),
  ship_address_addr3: varchar('ship_address_addr3', { length: 41 }),
  ship_address_addr4: varchar('ship_address_addr4', { length: 41 }),
  ship_address_addr5: varchar('ship_address_addr5', { length: 41 }),
  ship_address_city: varchar('ship_address_city', { length: 31 }),
  ship_address_state: varchar('ship_address_state', { length: 21 }),
  ship_address_postal_code: varchar('ship_address_postal_code', { length: 13 }),
  ship_address_country: varchar('ship_address_country', { length: 31 }),
  ship_address_note: varchar('ship_address_note', { length: 41 }),
  ship_address_block_addr1: varchar('ship_address_block_addr1', { length: 41 }),
  ship_address_block_addr2: varchar('ship_address_block_addr2', { length: 41 }),
  ship_address_block_addr3: varchar('ship_address_block_addr3', { length: 41 }),
  ship_address_block_addr4: varchar('ship_address_block_addr4', { length: 41 }),
  ship_address_block_addr5: varchar('ship_address_block_addr5', { length: 41 }),
  terms_ref_list_id: varchar('terms_ref_list_id', { length: 36 }),
  terms_ref_full_name: varchar('terms_ref_full_name', { length: 209 }),
  due_date: date('due_date'),
  expected_date: date('expected_date'),
  ship_method_ref_list_id: varchar('ship_method_ref_list_id', { length: 36 }),
  ship_method_ref_full_name: varchar('ship_method_ref_full_name', { length: 209 }),
  fob: varchar('fob', { length: 13 }),
  total_amount: numeric('total_amount', { precision: 12, scale: 2 }),
  currency_ref_list_id: varchar('currency_ref_list_id', { length: 36 }),
  currency_ref_full_name: varchar('currency_ref_full_name', { length: 209 }),
  exchange_rate: numeric('exchange_rate', { precision: 12, scale: 4 }),
  total_amount_in_home_currency: numeric('total_amount_in_home_currency', { precision: 12, scale: 2 }),
  is_manually_closed: boolean('is_manually_closed'),
  is_fully_received: boolean('is_fully_received'),
  memo: varchar('memo', { length: 4095 }),
  vendor_msg: varchar('vendor_msg', { length: 99 }),
  is_to_be_printed: boolean('is_to_be_printed'),
  is_to_be_emailed: boolean('is_to_be_emailed'),
  is_tax_included: boolean('is_tax_included'),
  sales_tax_code_ref_list_id: varchar('sales_tax_code_ref_list_id', { length: 36 }),
  sales_tax_code_ref_full_name: varchar('sales_tax_code_ref_full_name', { length: 209 }),
  other1: varchar('other1', { length: 25 }),
  other2: varchar('other2', { length: 29 }),
  external_guid: varchar('external_guid', { length: 36 }),
});

export type PurchaseOrders = typeof purchase_orders.$inferSelect;
export type NewPurchaseOrders = typeof purchase_orders.$inferInsert;
