// AUTO-GENERATED. DO NOT EDIT.
// Regenerate with: pnpm --filter @syntraodbc/drizzle-schema run generate
//
// Source: schemas/quickbooks.json
// Table:  vendors (79 columns)

import { pgTable, boolean, numeric, text, timestamp, varchar } from 'drizzle-orm/pg-core';

export const vendors = pgTable('vendors', {
  list_id: varchar('list_id', { length: 36 }),
  time_created: timestamp('time_created', { withTimezone: false, mode: 'string' }),
  time_modified: timestamp('time_modified', { withTimezone: false, mode: 'string' }),
  edit_sequence: varchar('edit_sequence', { length: 16 }),
  name: varchar('name', { length: 41 }),
  is_active: boolean('is_active'),
  class_ref_list_id: varchar('class_ref_list_id', { length: 36 }),
  class_ref_full_name: varchar('class_ref_full_name', { length: 209 }),
  is_tax_agency: boolean('is_tax_agency'),
  company_name: varchar('company_name', { length: 41 }),
  salutation: varchar('salutation', { length: 15 }),
  first_name: varchar('first_name', { length: 25 }),
  middle_name: varchar('middle_name', { length: 5 }),
  last_name: varchar('last_name', { length: 25 }),
  suffix: text('suffix'),
  job_title: varchar('job_title', { length: 41 }),
  vendor_address_addr1: varchar('vendor_address_addr1', { length: 41 }),
  vendor_address_addr2: varchar('vendor_address_addr2', { length: 41 }),
  vendor_address_addr3: varchar('vendor_address_addr3', { length: 41 }),
  vendor_address_addr4: varchar('vendor_address_addr4', { length: 41 }),
  vendor_address_addr5: varchar('vendor_address_addr5', { length: 41 }),
  vendor_address_city: varchar('vendor_address_city', { length: 31 }),
  vendor_address_state: varchar('vendor_address_state', { length: 21 }),
  vendor_address_postal_code: varchar('vendor_address_postal_code', { length: 13 }),
  vendor_address_country: varchar('vendor_address_country', { length: 31 }),
  vendor_address_note: varchar('vendor_address_note', { length: 41 }),
  vendor_address_block_addr1: varchar('vendor_address_block_addr1', { length: 41 }),
  vendor_address_block_addr2: varchar('vendor_address_block_addr2', { length: 41 }),
  vendor_address_block_addr3: varchar('vendor_address_block_addr3', { length: 41 }),
  vendor_address_block_addr4: varchar('vendor_address_block_addr4', { length: 41 }),
  vendor_address_block_addr5: varchar('vendor_address_block_addr5', { length: 41 }),
  ship_address_addr1: varchar('ship_address_addr1', { length: 41 }),
  ship_address_addr2: varchar('ship_address_addr2', { length: 41 }),
  ship_address_addr3: varchar('ship_address_addr3', { length: 41 }),
  ship_address_addr4: varchar('ship_address_addr4', { length: 41 }),
  ship_address_addr5: varchar('ship_address_addr5', { length: 41 }),
  ship_address_city: varchar('ship_address_city', { length: 31 }),
  ship_address_state: varchar('ship_address_state', { length: 21 }),
  ship_address_postal_code: varchar('ship_address_postal_code', { length: 13 }),
  ship_address_country: varchar('ship_address_country', { length: 31 }),
  ship_address_note: varchar('ship_address_note', { length: 41 }),
  phone: varchar('phone', { length: 21 }),
  mobile: varchar('mobile', { length: 21 }),
  pager: varchar('pager', { length: 21 }),
  alt_phone: varchar('alt_phone', { length: 21 }),
  fax: varchar('fax', { length: 21 }),
  email: varchar('email', { length: 1023 }),
  cc: varchar('cc', { length: 1023 }),
  contact: varchar('contact', { length: 41 }),
  alt_contact: varchar('alt_contact', { length: 41 }),
  name_on_check: varchar('name_on_check', { length: 41 }),
  account_number: varchar('account_number', { length: 99 }),
  notes: varchar('notes', { length: 4095 }),
  vendor_type_ref_list_id: varchar('vendor_type_ref_list_id', { length: 36 }),
  vendor_type_ref_full_name: varchar('vendor_type_ref_full_name', { length: 209 }),
  terms_ref_list_id: varchar('terms_ref_list_id', { length: 36 }),
  terms_ref_full_name: varchar('terms_ref_full_name', { length: 209 }),
  credit_limit: numeric('credit_limit', { precision: 12, scale: 2 }),
  vendor_tax_ident: varchar('vendor_tax_ident', { length: 15 }),
  is_vendor_eligible_for1099: boolean('is_vendor_eligible_for1099'),
  balance: numeric('balance', { precision: 12, scale: 2 }),
  billing_rate_ref_list_id: varchar('billing_rate_ref_list_id', { length: 36 }),
  billing_rate_ref_full_name: varchar('billing_rate_ref_full_name', { length: 209 }),
  external_guid: varchar('external_guid', { length: 36 }),
  sales_tax_code_ref_list_id: varchar('sales_tax_code_ref_list_id', { length: 36 }),
  sales_tax_code_ref_full_name: varchar('sales_tax_code_ref_full_name', { length: 209 }),
  is_sales_tax_agency: boolean('is_sales_tax_agency'),
  sales_tax_return_ref_list_id: varchar('sales_tax_return_ref_list_id', { length: 36 }),
  sales_tax_return_ref_full_name: varchar('sales_tax_return_ref_full_name', { length: 209 }),
  tax_registration_number: varchar('tax_registration_number', { length: 30 }),
  is_tax_tracked_on_purchases: boolean('is_tax_tracked_on_purchases'),
  tax_on_purchases_account_ref_list_id: varchar('tax_on_purchases_account_ref_list_id', { length: 36 }),
  tax_on_purchases_account_ref_full_name: varchar('tax_on_purchases_account_ref_full_name', { length: 209 }),
  is_tax_tracked_on_sales: boolean('is_tax_tracked_on_sales'),
  tax_on_sales_account_ref_list_id: varchar('tax_on_sales_account_ref_list_id', { length: 36 }),
  tax_on_sales_account_ref_full_name: varchar('tax_on_sales_account_ref_full_name', { length: 209 }),
  is_tax_on_tax: boolean('is_tax_on_tax'),
  currency_ref_list_id: varchar('currency_ref_list_id', { length: 36 }),
  currency_ref_full_name: varchar('currency_ref_full_name', { length: 209 }),
});

export type Vendors = typeof vendors.$inferSelect;
export type NewVendors = typeof vendors.$inferInsert;
